apiVersion: v1
kind: Secret
metadata:
  name: scm-ca-cert
  annotations:
  {{- range $key, $val := .Values.tags }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
data:
  {{ if .Values.scmCaCert }}
  scm_ca_cert.pem: {{ .Values.scmCaCert | b64enc | quote }}
  {{ else }}
  scm_ca_cert.pem: ""
  {{ end }}
